<a href="https://colab.research.google.com/github/ASO1801038/AI_teach2020/blob/master/20201009AI0205_selectAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.utils import all_estimators
import warnings

# データ読み込み
import urllib.request as req
url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/iris.csv"
savefile = "iris.csv"
req.urlretrieve(url,savefile)

iris_data = pd.read_csv("iris.csv", encoding="utf-8")

#ラベルと入力データに分離
y = iris_data.loc[:,"Name"]
x = iris_data.loc[:,["SepalLength","SepalWidth","PetalLength","PetalWidth"]]

# 学習用とテスト用に分離
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, train_size = 0.8, shuffle = True)

# classifierのアルゴ全取得
allAlgorithms = all_estimators(type_filter="classifier")
warnings.simplefilter("error")

for(name, algorithm) in allAlgorithms :
  try :
    # 各アリゴのオブジェクト作成
    clf = algorithm()

    # 学習、評価する
    clf.fit(x_train, y_train)
    y_pred = clf.predict(x_test)
    print(name,"の正解率 = " , accuracy_score(y_test, y_pred))
  
  #内容を表示
  except Warning as w :
    print("\033[33m"+"Warning："+"\033[0m", name, ":", w.args)
  except Exception as e :
    print("\033[31m"+"Error："+"\033[0m", name, ":", e.args)

AdaBoostClassifier の正解率 =  1.0
BaggingClassifier の正解率 =  1.0
BernoulliNB の正解率 =  0.3
Warning： CalibratedClassifierCV : ('Liblinear failed to converge, increase the number of iterations.',)
CategoricalNB の正解率 =  0.9666666666666667
Error： ClassifierChain : ("__init__() missing 1 required positional argument: 'base_estimator'",)
ComplementNB の正解率 =  0.7
DecisionTreeClassifier の正解率 =  1.0
Warning： DummyClassifier : ('The default value of strategy will change from stratified to prior in 0.24.',)
ExtraTreeClassifier の正解率 =  1.0
ExtraTreesClassifier の正解率 =  1.0
GaussianNB の正解率 =  1.0
GaussianProcessClassifier の正解率 =  1.0
GradientBoostingClassifier の正解率 =  1.0
HistGradientBoostingClassifier の正解率 =  1.0
KNeighborsClassifier の正解率 =  1.0
LabelPropagation の正解率 =  1.0
LabelSpreading の正解率 =  1.0
LinearDiscriminantAnalysis の正解率 =  1.0
Warning： LinearSVC : ('Liblinear failed to converge, increase the number of iterations.',)
LogisticRegression の正解率 =  1.0
Warning： LogisticRegressionCV : ('lbfgs failed

In [ ]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
import pandas as pd
from sklearn.utils import all_estimators
import warnings

iris_data = pd.read_csv("iris.csv", encoding="utf-8")

y = iris_data.loc[:,"Name"]
x = iris_data.loc[:,["SepalLength","SepalWidth","PetalLength","PetalWidth"]]

allAlgorithms = all_estimators(type_filter="classifier")

# K分割クロスバリデ用オブジェ
kfold_cv = KFold(n_splits=5, shuffle=True)
warnings.filterwarnings('ignore')

for(name, algorithm) in allAlgorithms :
  try :
    # 各アルゴオブジェ作成
    if(name == "LinearSVC") :
      clf = algorithm(max_iter = 10000)
    else:
      clf = algorithm()

    # scoreメソッドをもつクラスを対象
    if hasattr(clf,"score"):
        # クロスバリデ
        scores = cross_val_score(clf, x, y, cv=kfold_cv)
        print(name,"の正解率=")
        print(scores)
  
  except Exception as e :
    pass

AdaBoostClassifier の正解率=
[0.9        0.9        0.96666667 0.93333333 0.9       ]
BaggingClassifier の正解率=
[0.93333333 0.96666667 0.93333333 0.96666667 0.96666667]
BernoulliNB の正解率=
[0.3        0.3        0.26666667 0.26666667 0.16666667]
CalibratedClassifierCV の正解率=
[0.9        0.93333333 0.9        0.93333333 0.9       ]
CategoricalNB の正解率=
[0.96666667 0.96666667 0.9        0.83333333 0.96666667]
ComplementNB の正解率=
[0.53333333 0.6        0.7        0.7        0.8       ]
DecisionTreeClassifier の正解率=
[0.93333333 0.93333333 1.         0.96666667 0.9       ]
DummyClassifier の正解率=
[0.3        0.4        0.36666667 0.4        0.3       ]
ExtraTreeClassifier の正解率=
[0.93333333 0.96666667 0.93333333 0.96666667 0.96666667]
ExtraTreesClassifier の正解率=
[0.93333333 0.96666667 0.96666667 0.93333333 0.96666667]
GaussianNB の正解率=
[0.93333333 0.93333333 0.93333333 0.96666667 1.        ]
GaussianProcessClassifier の正解率=
[0.93333333 0.96666667 0.93333333 1.         0.93333333]
GradientBoostingClassifier の

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

iris_data = pd.read_csv("iris.csv", encoding="utf-8")

y = iris_data.loc[:,"Name"]
x = iris_data.loc[:,["SepalLength","SepalWidth","PetalLength","PetalWidth"]]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, train_size = 0.8, shuffle = True)

# グリッドサーチで利用するパラ指定
parameters = [
    {"C": [1, 10, 100, 1000], "kernel":["linear"]},
    {"C": [1, 10, 100, 1000], "kernel":["rbf"], "gamma":[0.001, 0.0001]},
    {"C": [1, 10, 100, 1000], "kernel":["sigmoid"], "gamma": [0.001, 0.0001]}
]

# グリッドサーチ
kfold_cv = KFold(n_splits=5, shuffle=True)
clf = GridSearchCV( SVC(), parameters, cv=kfold_cv)
clf.fit(x_train, y_train)
print("最適なパラメータ = ", clf.best_estimator_)

#評価
y_pred = clf.predict(x_test)
print("グリッドサーチの正解率 = " , accuracy_score(y_test, y_pred))


最適なパラメータ =  SVC(C=1000, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
グリッドサーチの正解率 =  1.0


In [ ]:
#numpyの操作確認
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

b = np.array([[1,2,3],[4,5,6]])
print(b)

#0埋め初期化
print(np.zeros(10))
print(np.zeros((3,2)))
print(np.zeros(2))

#要素を指定して初期化
print(np.arange(5))
print(np.arange(2,9))
print(np.arange(5,8,0.5))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0.]
[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


In [ ]:
#行列
a = np.array([1,2,3,4,5])
b = a*2
print(b)

x = np.array(10)
print(x)
y = 3*x+5
print(y)

#次元
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

#次元変換
a = np.array([[1,2,3],[4,5,6]])
print("a = ",a)
b = a.flatten()
print("b = ",b)

#回転
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = a.reshape(3,2)
print(b)

[ 2  4  6  8 10]
10
35
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
a =  [[1 2 3]
 [4 5 6]]
b =  [1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
v = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = v[0]
print(a)
b = v[1:]
print(b)
c = v[:,0]
print(c)

[1 2 3]
[[4 5 6]
 [7 8 9]]
[1 4 7]
